### Transform AAPL Data

In [20]:
%run ../../_config/base/base.ipynb

In [21]:
%run ../../_util/core/core.ipynb

### Load Data

In [22]:
AAPL_Data = pd.read_csv("../../Data/StockData/AAPL")
AAPL_News_Data = pd.read_csv("../../Data/NewsData/AAPL")
print(AAPL_Data.head(20))
print(AAPL_News_Data.head(20))

          Date        Open        High         Low       Close     Volume  \
0   2022-11-01  154.823169  155.192551  148.883026  150.400497   80379300
1   2022-11-02  148.703316  151.917985  144.759861  144.789810   93604600
2   2022-11-03  141.824736  142.563516  138.520220  138.650009   97918500
3   2022-11-04  142.089996  142.669998  134.380005  138.380005  140716700
4   2022-11-07  137.110001  139.149994  135.669998  138.919998   83374600
5   2022-11-08  140.410004  141.429993  137.490005  139.500000   89908500
6   2022-11-09  138.500000  138.550003  134.589996  134.869995   74917800
7   2022-11-10  141.240005  146.869995  139.500000  146.869995  118854000
8   2022-11-11  145.820007  150.009995  144.369995  149.699997   93903800
9   2022-11-14  148.970001  150.279999  147.429993  148.279999   73374100
10  2022-11-15  152.220001  153.589996  148.559998  150.039993   89868300
11  2022-11-16  149.130005  149.869995  147.289993  148.789993   64218300
12  2022-11-17  146.429993  151.479996  146.149994  150.720001   80389400
13  2022-11-18  152.309998  152.699997  149.970001  151.289993   74794600

    Dividends  Stock Splits
0        0.00             0
1        0.00             0
2        0.00             0
3        0.23             0
4        0.00             0
5        0.00             0
6        0.00             0
7        0.00             0
8        0.00             0
9        0.00             0
10       0.00             0
11       0.00             0
12       0.00             0
13       0.00             0
   Unnamed: 0        Date                                      Headline Data  \
0           0  2022-11-01  After Hours Most Active for Nov 1, 2022 : SHV,...
1           1  2022-11-01  Spotify is going to war with Apple after the A...
2           2  2022-11-01  Dow closes 500 points lower, Nasdaq sheds 3% a...
3           3  2022-11-01  Apple supplier Foxconn quadruples bonuses to s...
4           4  2022-11-01  After Hours Most Active for Oct 28, 2022 : SHV...
5           5  2022-11-01  Pre-Market Most Active for Oct 28, 2022 : TQQQ...
6           6  2022-11-01  Wall St slips as jobs data dents hopes for Fed...
7           7  2022-11-01  Apple Up Nearly 8%, on Pace for Largest Percen...
8           8  2022-11-01  Shanghai Disney visitors told to stay home aft...
9           9  2022-11-01  2 Apple executives, including one who has been...

  Article Published Date  Article Publisher
0            3 weeks ago                NaN
1            3 weeks ago                NaN
2            2 weeks ago                NaN
3            3 weeks ago                NaN
4            3 weeks ago                NaN
5            3 weeks ago                NaN
6            3 weeks ago                NaN
7             1 week ago                NaN
8            3 weeks ago                NaN
9            3 weeks ago                NaN

### Merge Stock and News Data

In [25]:
df_merge = pd.merge(AAPL_Data, AAPL_News_Data, how="inner", on="Date")
df_merge.head(30)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Unnamed: 0,Headline Data,Article Published Date,Article Publisher
0,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,0,"After Hours Most Active for Nov 1, 2022 : SHV,...",3 weeks ago,NaN
1,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,1,Spotify is going to war with Apple after the A...,3 weeks ago,NaN
2,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,2,"Dow closes 500 points lower, Nasdaq sheds 3% a...",2 weeks ago,NaN
3,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,3,Apple supplier Foxconn quadruples bonuses to s...,3 weeks ago,NaN
4,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,4,"After Hours Most Active for Oct 28, 2022 : SHV...",3 weeks ago,NaN
5,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,5,"Pre-Market Most Active for Oct 28, 2022 : TQQQ...",3 weeks ago,NaN
6,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,6,Wall St slips as jobs data dents hopes for Fed...,3 weeks ago,NaN
7,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,7,"Apple Up Nearly 8%, on Pace for Largest Percen...",1 week ago,NaN
8,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,8,Shanghai Disney visitors told to stay home aft...,3 weeks ago,NaN
9,2022-11-01,154.823169,155.192551,148.883026,150.400497,80379300,0.0,0,9,"2 Apple executives, including one who has been...",3 weeks ago,NaN